#===============================================================================
# 服务定义
#===============================================================================
services:
  nginx-ssl:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - /etc/letsencrypt/live/marketing.lucyai.sale:/etc/letsencrypt/live/marketing.lucyai.sale:ro
      - /etc/letsencrypt/archive/marketing.lucyai.sale:/etc/letsencrypt/archive/marketing.lucyai.sale:ro
